receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

exporters:
  logging:
    logLevel: normal
  
  otlp/data-prepper-traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper-metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper-logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-logs]